#!/usr/bin/env bash
# Auto-generated by jarvis_leaderboard_uploader
# Edit this file to reproduce your benchmark results.
#
# Benchmark: AI-TextClass-mmlu_test_quiz-mmlu-test-acc
# Method   : AI
# Property : mmlu_test_quiz
# Dataset  : mmlu
# Split    : test
#
# Example steps (adapt as needed):
# pip install my_model_package
# python run.py
